### ISSUE TITLE
Unable to create record using associative array

### ISSUE THREAD

**Issue by mata-man** [tom--/dynamic-ar#8]
I'm unable to use an associative array for the dynamic AR attributes.
Here is the table: 

``` PHP
$this->createTable('{{%spreadsheet_item}}', [
    'id' => Schema::TYPE_PK,
    'parent_id' => Schema::TYPE_INTEGER . ' NOT NULL',
    'data' => 'LONGBLOB NOT NULL',
    'created_by' => Schema::TYPE_INTEGER . ' NOT NULL',
    'updated_by' => Schema::TYPE_INTEGER . ' NOT NULL',
    'alias_by' => Schema::TYPE_INTEGER . ' DEFAULT NULL',
    'created_at' => Schema::TYPE_INTEGER . ' NOT NULL',
    'updated_at' => Schema::TYPE_INTEGER . ' NOT NULL',
    'alias_at' => Schema::TYPE_INTEGER . ' DEFAULT NULL',
], $tableOptions);
```

Also, my model has the static function dynamicColumn() returning 'data' as the column name and i also have these rules:

```
        return [
            [['parent_id'], 'required'],
            [['parent_id', 'created_by', 'updated_by', 'alias_by', 'created_at', 'updated_at', 'alias_at'], 'integer']
        ];
```

When trying to save by the associative array

``` PHP
$item = new SpreadsheetItem([
   'parent_id' => 0,
    'data' => [
        'first_name' => 'Bob'
    ]
]);
$item->save();
```

I receive this integrity constraint error :
`Column 'data' cannot be null
The SQL being executed was: INSERT INTO`spreadsheet_item`(`parent_id`,`data`,`created_at`,`updated_at`,`created_by`,`updated_by`,`alias_at`,`alias_by`) VALUES (0, NULL, 1437431869, 1437431869, 487, 487, 1437431869, NULL)`

**Comment by mata-man** [comment]
It appears adding a condition of `is_array` on the `$value` and setting the `$ref` will allow the model to save. I should test out if  it works at a multi level associative array.

``` PHP
public function setAttribute($name, $value)
    {
        if(!is_array($value))
        {
            try {
                parent::__set($name, $value);

                return;
            } catch (UnknownPropertyException $ignore) {
            }       

            $path = explode('.', $name);
            $ref = &$this->_dynamicAttributes;

            // Walk forwards through $path to find the deepest key already set.
            do {
                $key = $path[0];
                if (isset($ref[$key])) {
                    $ref = &$ref[$key];
                    array_shift($path);
                } else {
                    break;
                }
            } while ($path);

            // If the whole path already existed then we can just set it.
            if (!$path) {
                $ref = $value;

                return;
            }

            // There is remaining path so we have to set a new leaf with the first
            // part of the remaining path as key. But first, if there is any path
            // beyond that then we need build an array to set as the new leaf value.
            while (count($path) > 1) {
                $key = array_pop($path);
                $value = [$key => $value];
            }
            $ref[$path[0]] = $value;
        }
        else
        {
            $ref = &$this->_dynamicAttributes;
            $ref[static::dynamicColumn()] = $value;
        }
    }
```

**Comment by tom--** [comment]
In a DynamicActiveRecord, the dynamic attributes are attributes of the model, not elements of your 'data' attribute. So to set a  'first_name' attribute:

``` php
$item = new SpreadsheetItem([
    'parent_id' => 0,
    'first_name' => 'Bob'
]);
$item->save();
```

or you can do `$item->first_name` = 'Bob'`.

**Comment by mata-man** [comment]
I believe this could cause issues as a model is developed. It requires an unnecessary constraint on dynamic columns name not being that of the models columns names. Unless it is a constraint of MariaDB, i don't see why one would be added.

It can also cause confusion of which one is a true column when viewing the model in use.

**Comment by tom--** [comment]
There can be no conflict. According to dynamic-ar's [design principle](http://tom--.github.io/dynamic-ar/#design-principle), if there is a column attribute named 'foo' then a dynamic attribute called 'foo' cannot exist. Column attributes always take precedence.

If a developer uses a model that has column attribute 'foo' and and uses this model and its foo attribute thinking that it is dynamic, that's an incompetence for which dynamic-ar denies responsibility.

The purpose of dynamic-ar is to provide dynamic attributes and allow them to function like other Model or ActiveRecord attributes. That's why they are not accessed via, in your example, the 'data' attribute. If that's all you want, an array that's stored in a column, then it is easier to not use dynamic-ar and store the array in the DB using json_en-/decode() in before-/afterSave()

**Comment by tom--** [comment]
@mata-man I'm inclined to close this issue because I think it resolves to a difference of opinion over requirements. You argue that dynamic attributes should be under one model attribute. I, otoh, want dynamic attributes to be model attributes.

I would welcome a discussion of the pros and cons of each option in the [yiiframework.com forum](http://www.yiiframework.com/forum/index.php/topic/63995-structured-dynamic-attributes-in-activerecord-for-sql-tables).
